"""
Database configuration and session management.
"""
from sqlalchemy import create_engine
from sqlalchemy.exc import OperationalError
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session
from typing import Generator

from .config import settings

# 创建数据库引擎
engine = create_engine(
    settings.DATABASE_URL,
    connect_args={"check_same_thread": False},  # SQLite 特定配置
    echo=settings.DEBUG  # 在调试模式下显示SQL语句
)

# 创建会话工厂
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# 创建基类
Base = declarative_base()


def get_db() -> Generator[Session, None, None]:
    """
    获取数据库会话的依赖注入函数。

    Yields:
        Session: SQLAlchemy数据库会话
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def create_tables():
    """Create only the core tables required for the application."""
    # Avoid importing optional models so extra tables are not generated by default.
    from .models import (
        User,
        UserBalance,
        RedeemCode,
        Purchase,
        CreditTransaction,
        EmailVerification,
        ReadingAnalyzeLog,
        AppRelease,
    )  # noqa: WPS433

    tables_to_create = [
        User.__table__,
        UserBalance.__table__,
        RedeemCode.__table__,
        Purchase.__table__,
        CreditTransaction.__table__,
        EmailVerification.__table__,
        ReadingAnalyzeLog.__table__,
        AppRelease.__table__,
    ]
    try:
        Base.metadata.create_all(bind=engine, tables=tables_to_create)
    except OperationalError as error:
        # When multiple workers initialise concurrently SQLite may raise
        # "table already exists" even with checkfirst; treat it as benign.
        if "already exists" not in str(error).lower():
            raise


def drop_tables():
    """删除所有表（谨慎使用）。"""
    from .models import (
        User,
        UserBalance,
        RedeemCode,
        Purchase,
        CreditTransaction,
        EmailVerification,
        ReadingAnalyzeLog,
        AppRelease,
    )  # noqa: WPS433

    tables_to_drop = [
        User.__table__,
        UserBalance.__table__,
        RedeemCode.__table__,
        Purchase.__table__,
        CreditTransaction.__table__,
        EmailVerification.__table__,
        ReadingAnalyzeLog.__table__,
        AppRelease.__table__,
    ]
    Base.metadata.drop_all(bind=engine, tables=tables_to_drop)
